# Generated by Django 2.1.1 on 2018-09-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bulletsweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclists', models.PositiveIntegerField(default=0)),
                ('runners', models.PositiveIntegerField(default=0)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
            ],
            options={
                'permissions': (('manage_settings', 'Manage Permissions'),),
            },
        ),
    ]
