# Generated by Django 2.1.1 on 2018-09-20 21:56

from django.db import migrations
from django.conf import settings


def create_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SiteSettings = apps.get_model('bulletsweb', 'SiteSettings')

    for site in Site.objects.filter(settings__isnull=True):
        SiteSettings.objects.get_or_create(
            site=site,
            defaults={})


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0002_sitesettings'),
    ]

    operations = [
        migrations.RunPython(create_default_site,
                             lambda app, schema_editor: None)
    ]
