# Generated by Django 2.1.1 on 2018-09-20 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0003_auto_20180920_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycache',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='activitycache',
            name='start_date',
        ),
        migrations.AddField(
            model_name='activitycache',
            name='athlete',
            field=models.CharField(default='default athlete', max_length=1000, verbose_name='Athlete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitycache',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Activity Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitycache',
            name='name',
            field=models.CharField(default='default name', max_length=1000, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
