# Generated by Django 2.2 on 2020-08-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0004_auto_20180920_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('bullet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bulletsweb.Bullet')),
                ('rider', models.BooleanField(default=False, verbose_name='ride leader?')),
                ('runner', models.BooleanField(default=False, verbose_name='run leader?')),
                ('email_preference', models.BooleanField(default=True, verbose_name='Email me?')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('show_sat_rides', models.BooleanField(default=True, verbose_name='Show Saturday Rides?')),
                ('show_sun_rides', models.BooleanField(default=True, verbose_name='Show Sunday Rides?')),
            ],
        ),
    ]
