# Generated by Django 2.2 on 2020-08-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0005_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSpeedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='speed')),
                ('display_order', models.SmallIntegerField(default=1, verbose_name='display order')),
                ('group_type', models.CharField(choices=[('run', 'run'), ('ride', 'ride')], default='run', max_length=4)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='speed')),
                ('display_order', models.SmallIntegerField(default=1, verbose_name='display order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeds', to='bulletsweb.BulletEvent')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leading', models.NullBooleanField(default=None)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletsweb.BulletEvent')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletsweb.Leader')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speed_plan', to='bulletsweb.EventSpeed')),
                ('speed_options', models.ManyToManyField(blank=True, to='bulletsweb.EventSpeed')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['leader', 'plan'],
            },
        ),
    ]
