# Generated by Django 2.2 on 2020-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0006_availability_defaultspeedgroup_eventspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletevent',
            name='have_sent_email',
            field=models.BooleanField(default=False, verbose_name='Have chased leaders about this event'),
        ),
    ]
