# Generated by Django 2.2 on 2020-08-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsweb', '0007_bulletevent_have_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletevent',
            name='have_sent_initial_email',
            field=models.BooleanField(default=False, verbose_name='Have told leaders about this event'),
        ),
    ]
