# Generated by Django 2.1.1 on 2018-09-22 22:24

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0002_auto_20180922_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='bulletsshop.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='productitem',
            name='extra_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Item Name'),
        ),
    ]
