# Generated by Django 2.1.1 on 2018-09-23 19:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0003_auto_20180922_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('postcode', models.CharField(max_length=8, verbose_name='PostCode')),
                ('postage_required', models.BooleanField(default=False, verbose_name='Must be posted to buyer?')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Order created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Order last updated')),
                ('unique_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email links')),
                ('status', models.CharField(choices=[('U', 'Not paid'), ('P', 'Paid'), ('C', 'Complete'), ('X', 'Cancelled'), ('R', 'Refunded')], default='U', max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Waiting for stock'), ('G', 'Ready to despatch'), ('D', 'Despatched'), ('X', 'Cancelled'), ('R', 'Returned / Refunded')], default='G', max_length=1, verbose_name='Status')),
                ('item_name', models.CharField(max_length=1000, verbose_name='Name')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity_ordered', models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_allocated', models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_delivered', models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to='bulletsshop.ProductItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bulletsshop.Order')),
            ],
        ),
    ]
