# Generated by Django 2.1.1 on 2018-09-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postage_required',
        ),
        migrations.AddField(
            model_name='order',
            name='postage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Postage'),
            preserve_default=False,
        ),
    ]
