# Generated by Django 2.1.1 on 2018-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0005_auto_20180923_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_postage_required',
            field=models.BooleanField(default=False, verbose_name='Must be posted to buyer?'),
        ),
    ]
