# Generated by Django 2.1.1 on 2018-09-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0007_auto_20180925_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Basket created')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bulletsshop.Basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='bulletsshop.ProductItem')),
            ],
        ),
    ]
