# Generated by Django 2.1.1 on 2018-09-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='postage_required',
        ),
        migrations.AddField(
            model_name='product',
            name='postage_option',
            field=models.CharField(choices=[('P', 'Postage required'), ('O', 'Postage optional'), ('X', 'Postage not permitted')], default='O', max_length=1, verbose_name='Postage'),
        ),
        migrations.AddField(
            model_name='product',
            name='postage_amount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletsshop.Postage'),
        ),
    ]
