# Generated by Django 2.1.1 on 2018-09-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0011_auto_20180928_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postage_amount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bulletsshop.Postage'),
        ),
    ]
