# Generated by Django 2.1.1 on 2018-09-30 18:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0014_auto_20180929_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_allocated',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_refunded',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
