# Generated by Django 2.1.1 on 2018-10-01 21:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0015_auto_20180930_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='quantity_allocated',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_allocated',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
