# Generated by Django 2.1.1 on 2018-10-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0016_auto_20181001_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
