# Generated by Django 2.1.1 on 2018-10-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0017_remove_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Comment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bulletsshop.Order')),
            ],
        ),
    ]
