# Generated by Django 2.1.4 on 2019-01-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0019_auto_20190105_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('event', models.CharField(choices=[('c', 'Created'), ('d', 'Dispatched'), ('o', 'Ordered'), ('r', 'Received'), ('x', 'Refunded')], default='c', max_length=1, verbose_name='Event')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bulletsshop.ProductItem')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
