# Generated by Django 2.1.4 on 2019-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0021_auto_20190113_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_chase',
            field=models.BooleanField(default=False, verbose_name='Has stale order been chased via email?'),
        ),
    ]
