# Generated by Django 2.1.5 on 2019-02-02 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0022_order_email_chase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500, verbose_name='Voucher Code')),
                ('number_of_uses', models.IntegerField(default=1, verbose_name='How many times voucher can be used')),
                ('used_count', models.IntegerField(default=0, verbose_name='Number of times voucher has been used')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('available_from', models.DateField(default=datetime.date.today, verbose_name='Available on or after this date')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name='Available until this date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('products', models.ManyToManyField(to='bulletsshop.Product')),
            ],
        ),
    ]
