# Generated by Django 2.1.5 on 2019-02-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0023_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=500, unique=True, verbose_name='Voucher Code'),
        ),
    ]
