# Generated by Django 2.1.5 on 2019-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0024_auto_20190203_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='products',
            field=models.ManyToManyField(blank=True, to='bulletsshop.Product'),
        ),
    ]
