# Generated by Django 3.1 on 2020-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletsshop', '0027_auto_20191103_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['display_order', 'extra_text']},
        ),
        migrations.AddField(
            model_name='productitem',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
    ]
